# Initial STD of Error-State values (filter)  P-Matrix
dp0_std: [0.02, 0.02, 0.05] #[0;0;0.05]
dv0_std: [0.002, 0.002, 0.002]  #[0;0;0]
dtheta0_std: [0.0002, 0.0002, 0.0002]   #5e-2*[1;1;1]
dab0_std: [0.0196, 0.0196, 0.0196]  #2e-3*9.8*[1;1;1]
dwb0_std: [0.0037, 0.0040, 0.004]   #dwb0_est_std = [0.0037;0.0040;0]; % Filter: error (yaw non observable)
dg0_std: [0.0005, 0.0005, 0.0005]


frame: global # Frame r.t. orientation derivation is computed (global or local)

#G STD values
g_std: [0.0,0.0,0.0]

#IMU STD values
imu_a_std: [0.002,0.002,0.002]    #a_est_std_cont = 0.2; % Sensor: Acc. noise. (High value due to vibrations)
imu_w_std: [0.005,0.005,0.005]    #w_est_std_cont = 0.005; % Sensor: Gyros. noise.   
imu_ab_std: [0.002,0.002,0.002]     
imu_wb_std: [0.004,0.004,0.004]     
imu_method: discrete #Sets the data time nature (continous: simulated IMU or discrete: IMU sensor).

# Position STD values
position_std_outsidebounds: [10.0,10.0,10.0]
position_std_insidebounds: [0.01,0.01,0.01]

# Orientation STD values
orientation_std_outsidebounds: [10.0,10.0,10.0]
orientation_std_insidebounds: [0.01,0.01,0.01]

# Linear velocity STD values
linvel_std_outsidebounds: [10.0,10.0,10.0]
linvel_std_insidebounds: [0.01,0.01,0.01]

# Pose STD velaues (Pose field of Odometry msg)
pose_std_outsidebounds: [10.0,10.0,10.0,10.0,10.0,10.0]
pose_std_insidebounds: [0.01,0.01,0.01,0.01,0.01,0.01]

# Pose 2 STD velaues (Pose field of Odometry 2 msg)
pose2_std_outsidebounds: [10.0,10.0,10.0,10.0,10.0,10.0]
pose2_std_insidebounds: [0.01,0.01,0.01,0.01,0.01,0.01]

# Range STD values
range_std_outsidebounds: 10.0
range_std_insidebounds: 0.01
range_min: 0.31
range_max: 4.0
using_laser_range: true

# Initial Nominal-State vector (p,v,q,ab,wb,g)
# xstate0: [0.0,0.0,0.15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-9.803057,0.0,0.0,-0.1,0.0,0.0,0.0,1.0,0.0,0.0,-0.1,1.0,0.0,0.0,0.0]
# xstate0: [0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0005,-0.0026,-0.0004,0.0,0.0,-9.803057] #external_state 19  #wb0_est = [-0.0005;-0.0026;-0.0004]; % Filter: nominal
xstate0: [0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-9.803057] #external_state 19  #wb0_est = [-0.0005;-0.0026;-0.0004]; % Filter: nominal


# Initial Error-State vector (dp,dv,dtheta,dab,dwb,dg)
# dxstate0: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
dxstate0: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0] #internal_state 18